import tkinter as tk
from tkinter import messagebox
root = tk.Tk()
root.title("Formularz rejestracyjny zgłoszenia na festiwal")
# Etykiety i pola tekstowe
label_title = tk.Label(root, text="Imię")
label_title.grid(row=0, column=0, padx=10, pady=5, sticky="w")
entry_title = tk.Entry(root, width=40)
entry_title.grid(row=0, column=1, padx=10, pady=5)
label_author = tk.Label(root, text="Nazwisko")
label_author.grid(row=1, column=0, padx=10, pady=5, sticky="w")
entry_author = tk.Entry(root, width=40)
entry_author.grid(row=1, column=1, padx=10, pady=5)
label_genre = tk.Label(root, text="Adres-email")
label_genre.grid(row=2, column=0, padx=10, pady=5, sticky="w")
entry_genre = tk.Entry(root, width=40)
entry_genre.grid(row=2, column=1, padx=10, pady=5)
label_year = tk.Label(root, text="Numer telefonu")
label_year.grid(row=3, column=0, padx=10, pady=5, sticky="w")
entry_year = tk.Entry(root, width=40)
entry_year.grid(row=3, column=1, padx=10, pady=5)
label_city = tk.Label(root, text="Miasto")
label_city.grid(row=4, column=0, padx=10, pady=5, sticky="w")
entry_city = tk.Entry(root, width=40)
entry_city.grid(row=4, column=1, padx=10, pady=5)
label_country = tk.Label(root, text="Kraj")
label_country.grid(row=5, column=0, padx=10, pady=5, sticky="w")
entry_country = tk.Entry(root, width=40)
entry_country.grid(row=5, column=1, padx=10, pady=5)
label_bdate = tk.Label(root, text="Data urodzenia")
label_bdate.grid(row=6, column=0, padx=10, pady=5, sticky="w")
entry_bdate = tk.Entry(root, width=40)
entry_bdate.grid(row=6, column=1, padx=10, pady=5)
# Przycisk zapisu


button_save = tk.Button(root, text="Zapisz", command=lambda x:x)
button_save.grid(row=7, column=0, columnspan=2, pady=10)
# Uruchomienie pętli głównej
root.mainloop()