import tkinter as tk
from tkinter import messagebox
root = tk.Tk()
root.title("Formularz rejestracyjny zgłoszenia na festiwal")
# Etykiety i pola tekstowe
label_imie = tk.Label(root, text="Imię")
label_imie.grid(row=0, column=0, padx=10, pady=5, sticky="w")
entry_imie = tk.Entry(root, width=40)
entry_imie.grid(row=0, column=1, padx=10, pady=5)
label_surname = tk.Label(root, text="Nazwisko")
label_surname.grid(row=1, column=0, padx=10, pady=5, sticky="w")
entry_surname = tk.Entry(root, width=40)
entry_surname.grid(row=1, column=1, padx=10, pady=5)
label_mail = tk.Label(root, text="Adres-email")
label_mail.grid(row=2, column=0, padx=10, pady=5, sticky="w")
entry_mail = tk.Entry(root, width=40)
entry_mail.grid(row=2, column=1, padx=10, pady=5)
label_year = tk.Label(root, text="Numer telefonu")
label_year.grid(row=3, column=0, padx=10, pady=5, sticky="w")
entry_year = tk.Entry(root, width=40)
entry_year.grid(row=3, column=1, padx=10, pady=5)
label_city = tk.Label(root, text="Miasto")
label_city.grid(row=4, column=0, padx=10, pady=5, sticky="w")
entry_city = tk.Entry(root, width=40)
entry_city.grid(row=4, column=1, padx=10, pady=5)
label_country = tk.Label(root, text="Kraj")
label_country.grid(row=5, column=0, padx=10, pady=5, sticky="w")
entry_country = tk.Entry(root, width=40)
entry_country.grid(row=5, column=1, padx=10, pady=5)
label_bdate = tk.Label(root, text="Data urodzenia")
label_bdate.grid(row=6, column=0, padx=10, pady=5, sticky="w")
entry_bdate = tk.Entry(root, width=40)
entry_bdate.grid(row=6, column=1, padx=10, pady=5)
label_ID = tk.Label(root, text="PESEL")
label_ID.grid(row=7, column=0, padx=10, pady=5, sticky="w")
label_ID = tk.Entry(root, width=40)
label_ID.grid(row=7, column=1, padx=10, pady=5)
label_DG = tk.Label(root, text="Wykształcenie")
label_DG.grid(row=8, column=0, padx=10, pady=5, sticky="w")
label_DG = tk.Entry(root, width=40)
label_DG.grid(row=8, column=1, padx=10, pady=5)
label_EX = tk.Label(root, text="Doświadczenie wolontariackie")
label_EX.grid(row=9, column=0, padx=10, pady=5, sticky="w")
label_EX = tk.Entry(root, width=40)
label_EX.grid(row=9, column=1, padx=10, pady=5)
label_bdate = tk.Label(root, text="Języki obce")
label_bdate.grid(row=10, column=0, padx=10, pady=5, sticky="w")
entry_bdate = tk.Entry(root, width=40)
entry_bdate.grid(row=10, column=1, padx=10, pady=5)
label_ID = tk.Label(root, text="Preferencje wolontariackie")
label_ID.grid(row=11, column=0, padx=10, pady=5, sticky="w")
label_ID = tk.Entry(root, width=40)
label_ID.grid(row=11, column=1, padx=10, pady=5)
label_DG = tk.Label(root, text="Rozmiar koszulki")
label_DG.grid(row=12, column=0, padx=10, pady=5, sticky="w")
label_DG = tk.Entry(root, width=40)
label_DG.grid(row=12, column=1, padx=10, pady=5)
label_EX = tk.Label(root, text="Dlaczego chcesz być wolontariuszem?")
label_EX.grid(row=13, column=0, padx=10, pady=5, sticky="w")
label_EX = tk.Entry(root, width=40)
label_EX.grid(row=13, column=1, padx=10, pady=5)
label_dod = tk.Label(root, text="Skąd dowiedziałeś się o wydarzeniu?")
label_dod.grid(row=14, column=0, padx=10, pady=5, sticky="w")
label_dod = tk.Entry(root, width=40)
label_dod.grid(row=14, column=1, padx=10, pady=5)



# Przycisk zapisu


button_save = tk.Button(root, text="Zapisz", command=lambda x:x)

button_save.grid(row=15, column=0, columnspan=2, pady=10)
# Uruchomienie pętli głównej
root.mainloop()